### PR TITLE
Specify default directory when starting the backend

### LINKED ISSUE #3: [MacOS] `grep` and `find` commands are run in the user's home folder, rather than the current / project folder
Hi!

Thanks for creating this! I'm running into some issues with the commands, as the `grep` and `find` operations are being performed on my home directory, rather than the current / project directory. I'm probably missing something obvious here. Is there some place where I can start debugging this?

---

I could replicate this with two configurations, on a macOS system running emacs 28:
- Using straight (results surfaced using `selectrum`)
```elisp
  (use-package affe
    :straight (:host github :repo "minad/affe" )
    :after (orderless consult)
    :custom (
             (affe-regexp-function #'orderless-pattern-compiler)
             (affe-highlight-function #'orderless-highlight-matches)
             (affe-find-command "fd"))
    :config
    ;; Manual preview key for `affe-grep'
    (setf (alist-get #'affe-grep consult-config) `(:preview-key ,(kbd "M-."))))
```
- Following the instructions you wrote up in https://github.com/minad/affe/issues/1#issuecomment-844903933 (results surfaced using `icomplete-vertical`)

### PR DESCRIPTION
**Pull request by rajk04**
Fixes #3

I've tested this on a mac, and it works as expected. I'll test this on linux and tramp later today / tomorrow as well, to ensure that I haven't broken anything.

### CODE REVIEW

**Comment by minad** [comment]
Can you please report this as a bug with report-emacs-bug?

**Comment by rajk04** [comment]
Sorry, I got a bit delayed here. I have reported the bug using `report-emacs-bug`, and shall add a link to the ticket once it shows up on debbugs (this is the first time I've done this, so I'm not sure when it would show up).

**Comment by minad** [comment]
@rajk04 You should receive a confirmation email within a few minutes.

**Comment by rajk04** [comment]
Got it! It's filed under [Debbugs 48579](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=48579), and I received a response from the maintainers! Their recommendation is to explicitly switch directories in this case (more details on the bug report)

**Pull request merged**
